services:
  postgres:
    image: postgres
    container_name: algorithms-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PW}
      POSTGRES_PORT: ${POSTGRE_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRE_PORT}:${POSTGRE_PORT}"
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: algorithms-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_MAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PW}
    volumes:
      - pgadmindata:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:${PGADMIN_PORT}"
    restart: always

  redis:
    image: redis
    container_name: algorithms-redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redisdata:/data
    restart: always

  server:
    image: redis/redisinsight
    container_name: algorithms-redis-insight
    ports:
      - "${REDISINSIGHT_PORT}:${REDISINSIGHT_PORT}"
    environment:
      SERVER_HOST: ${REDISINSIGHT_PORT}
      SERVER_PORT: ${REDISINSIGHT_PORT}
    restart: always

volumes:
  pgdata:
  pgadmindata:
  redisdata: