name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          docker compose version || (
            sudo apt-get update
            sudo apt-get install docker-compose-plugin -y
          )

      - name: Start PostgreSQL
        run: docker compose up -d postgres

      - name: Run Integration Tests
        run: mvn integration-test -Dspring.datasource.url=jdbc:postgresql://localhost:5432/postgres -Dspring.datasource.username=${{ secrets.POSTGRES_USER }} -Dspring.datasource.password=${{ secrets.POSTGRES_PW }}

      - name: Stop PostgreSQL
        if: always()
        run: docker compose down
