name: Integration Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Docker Compose
        run: |
          docker compose version || (
            sudo apt-get update
            sudo apt-get install docker-compose-plugin -y
          )

      - name: Start compose
        run: docker compose up

      - name: Run Integration Tests
        run: mvn integration-test

      - name: Stop compose
        if: always()
        run: docker compose down
